opensciencegrid/osgvo-docker-pilot

.github/workflows/build-container.yml
Dockerfile

@brianhlin 
Largely based on the docker-frontier-squid workflow.
I am not sure if `opensciencegrid/osgvo-docker-pilot` is the right name for the dockerhub repo.

add build-container workflow (SOFTWARE-4250)

---

README.md

- Fix missing backslash
- Recommend `:release` container

Misc README fixes

---

.github/workflows/build-container.yml

Add the ability to trigger new workflow runs from the UI.

Add workflow_dispatch (SOFTWARE-4672)

---

10-setup-htcondor.sh
50-main.config
Dockerfile
condor_master_wrapper

Moved from the old osg-flock scripts to the current GWMS singularity … (SOFTWARE-4725)

---

.github/workflows/build-container.yml
tests/test_inside_gha.sh

Third PR's the charm? Supersedes #31 and #29

Add Docker backfill CI tests (SOFTWARE-4726)

---

10-setup-htcondor.sh
Dockerfile

Also, move GlideinWMS script dir structure creation to the Dockerfile. Still testing this change on Tiger.

Ensure that we run per-job module setup (SOFTWARE-4819, OSPOOl-6)

---

tests/test_inside_gha.sh

Unsurprisingly, this works and now we can test it!
EDIT: Reading over the ticket, it sounds like we can try reduced caps for the `cvmfsexec` case now that we moved over to the GlideinWMS Singularity scripts in #28

Test reduced capabilities (SOFTWARE-4477)

---

Dockerfile

Same as #37 with a commit message attached to a Jira ticket

Install attr for CVMFS error detection (SOFTWARE-4834)

---

10-setup-htcondor.sh
Dockerfile

- Install git along with the other RPMs to avoid creating a yum cache
- Download osgvo scripts in a separate layer than the RPM installs

Small Dockerfile tweaks

---

10-setup-htcondor.sh
rsyslog.conf

Per suggestion from @matyasselmeci - add the GLIDEIN_Site and GLIDEIN_ResourceName variables into the structured metadata.

Add glidein metadata to rsyslog outputs.

---

10-setup-htcondor.sh
Dockerfile

- Fix indent
- Don't set up remote syslog if we can't find SYSLOG_HOST

Don't set up remote syslog if we can't find SYSLOG_HOST

---

10-setup-htcondor.sh

Get rid of illegal characters, chop off all leading/trailing dots/dashes, truncate so that NETWORK_HOSTNAME <= 63 chars

Sanitize GLIDEIN_ResourceName before using it as NETWORK_HOSTNAME

---

.github/workflows/build-container.yml
Dockerfile
tests/test_inside_gha.sh

- Adds release series specific tags (SOFTWARE-4944)
- Removes ITB tags, these were interfering with flux wildcards anyway
Working build/test here: https://opensciencegrid.atlassian.net/browse/SOFTWARE-4944

Use standard OSG container actions 

---

tests/test_inside_gha.sh

```
$( ( ...
```
means start a subshell
```
$(( ...
```
means evaluate arithmetic

Fix setting CVMFS_REPOSITORIES in the tests:

---

10-setup-htcondor.sh

This lets users know which knob to change

Tweak hold reason for excessive disk usage

---

10-setup-htcondor.sh

so we don't collide with anything else on the machine
(SOFTWARE-5230)

Let the OS pick a random shared port port

---

10-setup-htcondor.sh
Dockerfile

Also fixed a stashcp issue when stashcp is installed in the image, and a escaping issue when writing out the HTCondor config file.

Use the new CCB servers for the OSPool

---

Dockerfile

use glideinwms:master rather than branch_v3_9 (SOFTWARE-5340)

---

Dockerfile

at least until we can get https://github.com/glideinWMS/glideinwms/pull/233 merged upstream

use carl's fixes for singularity_lib.sh (SOFTWARE-5340)

---

Dockerfile

For use in scripts we download from the osg-flock repo
(SOFTWARE-5363)

Add IS_CONTAINER_PILOT=1 to the environment

---

10-setup-htcondor.sh

it's a directory, it should have +x

Fix perms on SEC_CREDENTIAL_DIRECTORY

---

.github/workflows/build-container.yml

Fix missing push to Docker Hub (SOFTWARE-5368)

---

10-setup-htcondor.sh
Dockerfile

Our desired changes (glideinWMS#233) got merged

Use upstream glideinwms repo and master branch again

---

Dockerfile

Off by default unless CONTAINER_PILOT_USE_JOB_HOOK is set
Depends on https://github.com/opensciencegrid/osg-flock/pull/220 being merged first

Install the new job hook

---

Dockerfile
entrypoint.sh
tests/test_inside_gha.sh

Use CVMFSEXEC 4.30 to avoid a bug in 4.31

---

Dockerfile
entrypoint.sh
tests/test_inside_gha.sh

Also includes some reorganization of entrypoint.sh.

Add a CVMFSEXEC_DEBUG knob to enable debugging of CVMFSEXEC

---

.github/workflows/build-container.yml

Add OSG 23 images (SOFTWARE-5763)

---

10-setup-htcondor.sh

Apparently, the scripts in osg-flock have taken care of it since version 741 or so: https://github.com/opensciencegrid/osg-flock/pull/272

Drop redundant OSDF plugin detection

---

50-main.config

This is part of https://github.com/opensciencegrid/osgvo-docker-pilot/pull/193

Allow the local user to run condor_off, condor_reconfig, etc.
