- 10-htcondor.conf
- Dockerfile
- supervisord.conf
Purdue is seeing issues where the container can't write to `/var/log`. I'm asking them to test these changes
> Throw away supervisord logs to support unpriv containers

- 50-main.config
Noticed these when troubleshooting Chameleon cloud's idle slots. Perhaps related: Lancium is also seeing their backfill containers sitting idle.
@rynge what sets `MY.OSG_NODE_VALIDATED`? It doesn't appear to be set in the Chameleon container or one of the JetStream containers:
```
$ podman run --rm -it opensciencegrid/hosted-ce:release condor_status -pool flock.opensciencegrid.org -const '!isUndefined(IsOsgVoContainer) && isUndefined(osg_node_validated)' -af name
slot1@JetStream-1858bc205145
slot1@chameleon-uc-dev-backfill-383906f438aa
```
> Start expression fixups

- README.md
@DrDaveD says not having this might cause issues.
> Mount /cvmfs with :shared; without it, the host can't see automounted volumes

- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
Use /pilot instead of /tmp as the directory for putting all pilot-related stuff into; it's  chmodded 1777, just like /tmp, so ownership isn't a problem.
Tested this on tiger -- everything seems to start up successfully, but is there a way I can do further validation?
> Don't use /tmp as the local directory

- Dockerfile
- README.md
- entrypoint.sh
- Use cvmfsexec to mount CVMFS repos if needed
- Don't run crond (doesn't work as non-root)
- Create log files before tailing them to solve "<FILE> has been replaced witha remote file" error from tail
> Add cvmfsexec (SOFTWARE-4549)

- 10-setup-htcondor.sh
Add two environment variables to the setup script allowing dynamic configuration of the CCB port range.  
This is very useful for running against another collector, and can be used with
```
CCB_RANGE_LOW=9618
CCB_RANGE_HIGH=9618
```
to connect to a "default" collector without multiple CCBs configured.
Note: I'm assuming the default range should be [9700, 9899] inclusive.  It was written before as [9700, 9899) exclusive.
> allow CCB port range to be configurable

- 10-ldconfig-cache.sh
- Dockerfile
- ldconfig_wrapper.sh
(SOFTWARE-4807)
Work around for https://github.com/hpcng/singularity/issues/5759, courtesy of @DrDaveD 
We do this to ensure that GPU libs can be accessed by user containers.
In particular, the backfill container mounts the libs from the host to
'/.singularity.d/libs' (available in LD_LIBRARY_PATH).
ldconfig tries to write its cache to /etc/, which isn't possible if
the outer backfill container is started up with Singularity.
> Ensure that Nvidia libs are bind mounted into child containers

- 10-htcondor.conf
- 10-setup-htcondor.sh
- 50-main.config
- entrypoint.sh
Currently `STARTD_NOCLAIM_SHUTDOWN` is fixed at 30 minutes, and supervisord restarts condor repeatedly, never exiting the container.
This PR allows the idle time to be configured, and shuts down the container if `condor_master` exits normally.
> shut down an idle pilot

- 10-setup-htcondor.sh
- turn off xtrace (set -x) when using $TOKEN in an expression
- don't use it on the command line, pipe it through cat instead
- set it to a bogus value once we're done with it
> Avoid accidentally printing $TOKEN on the console

- entrypoint.sh
This lets you specify CVMFSEXEC_REPOS using either commas or spaces as a separator, not just spaces.
> Allow comma separated CVMFSEXEC_REPOS

- 10-rsyslogd.conf
- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
- condor_master_wrapper
- generate-hostcert
- launch_rsyslogd.c
- rsyslog.conf
- supervisord.conf
- supervisord_startup.sh
- tests/test_inside_gha.sh
This (a) adds a syslog daemon to the container (via a setuid binary
as syslog is immovably at `/dev/log`) and (b) tells all HTCSS daemons
to log to the container.
The syslog daemon is set to log to the supervisord stdout, resulting
in all HTCondor logs getting to the container's stdout in a timely
manner.
> Log *all* condor logs to stdout

- 10-setup-htcondor.sh
- generate-hostcert
- The sysadmin can override the registry hostname with the `REGISTRY_HOSTNAME` environment variable.
- If the known osgdev syslog server is used, automatically switch to the osgdev token registry.
> Allow the container to better manage the token registry hostname.

- 10-setup-htcondor.sh
Avoids issues if the /pilot directory is persistent
> Clean out the rsyslog directory prior to starting.

- rsyslog.conf
On failures (and in a few other situations), HTCondor will log categories along the lines of `(D_ALWAYS|D_FAILURE)`; add the pipe character (`|`) to the regexp to account for this situation.
> Make regexp more permissive.

- 10-setup-htcondor.sh
- Dockerfile
This is a copy, not a symlink, because the program uses argv[0] to determine its behavior.
> Use the single-binary stashcp as stash_plugin

- .github/workflows/build-container.yml
- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
https://opensciencegrid.atlassian.net/browse/SOFTWARE-5002
If you specify `--build-arg ITB=1` when building the container, it will use the itb versions of the osg-flock scripts and also add the attributes for joining the ITB pool.
Other features (intended for manual builds):
- specify your fork of osg-flock in the `OSG_FLOCK_REPO` var, e.g. `--build-arg OSG_FLOCK_REPO=matyasselmeci/osg-flock`
- specify the branch of osg-flock in the `OSG_FLOCK_BRANCH` var, e.g. `--build-arg OSG_FLOCK_BRANCH=mybranch`
- the above two args, as well as `OSG_FLOCK_HASH` (the git hash of the checkout) will be advertised in the startd ad
- specify `--build-arg RANDOM=$RANDOM` to use the docker build cache for the RPM install, but get a fresh checkout of the scripts. This saves a lot of time, especially on slow …
> ITB backfill container (SOFTWARE-5002)

- 10-setup-htcondor.sh
Verified that condor started up (I didn't have OSPool tokens handy) when setting `POOL` to nothing, `prod-ospool`, and `itb-ospool` were set. @ddavila0 is working on cm-2 for the PATh facility so that doesn't seem to work quite yet
> Add prod PATh facility choice to POOL (SOFTWARE-5004)

- 10-htcondor.conf
- 50-main.config
- Dockerfile
- master_shutdown.sh
I noticed that the current container did not shut down after exhausting the `ACCEPT_IDLE_MINUTES`/`ACCEPT_JOBS_FOR_HOURS` timeouts. HTCondor would exit, but restart by supervisord. This PR introduces a `DEFAULT_MASTER_SHUTDOWN_SCRIPT` script which runs `kill 1`, similar to the annex HTCondor documentation: https://htcondor.readthedocs.io/en/latest/cloud-computing/annex-customization-guide.html
> Ensure that the container shuts down correctly after idle/retirement

- 10-setup-htcondor.sh
1.  PATh facility CM `COLLECTOR962[0-3]_ARGS` knobs all have `-sock
collector962[0-3]`
1.  There appears to only be one collector port, 9619
> Add PATh facility CCB addresses (SOFTWARE-5070)

- 50-main.config
SOFTWARE-5048 originally called for adding just `want_mpi =!= true` to the `START` expression.
In the comments, @matyasselmeci then suggested `(TARGET.Want_MPI =!= True || MY.Has_MPI =?= True)` might be better, so I've added that instead.
> add "want_mpi =!= true" to START expression (SOFTWARE-5048)

- 10-setup-htcondor.sh
(which leads to 'mount source ... does not exist' errors, see https://github.com/apptainer/singularity/issues/5766)
> Unset SINGULARITY_BIND so that singularity-in-singularity doesn't attempt to propagate bind mounts from outside (SOFTWARE-5207)

- master_shutdown.sh
kill defaults to SIGTERM, but I found some pages [1,2] with examples killing supervisord specifically using SIGQUIT.  Could this be the key to what went wrong?
Then again, the supervisord docs suggest[1] that a number of signals including TERM will cause it to shut down, so I am not wildly confident this will actually fix it.
[1] https://serverfault.com/questions/760726/how-to-exit-all-supervisor-processes-if-one-exited-with-0-result
[2] https://hangarau.space/using-supervisord-as-the-init-process-of-a-docker-container/
[3] http://supervisord.org/running.html#signal-handlers
> kill supervisord with SIGQUIT (SOFTWARE-4608)

- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
This installs both the ITB and production scripts into separate directories. When the container is started with `-e ITB=1`, the ITB scripts will be used and the pilot will advertise itself as an ITB site and join the ITB pool.
This does not yet use `additional-htcondor-config` or the `prepare-job` hook, and it uses the old singularity wrapper for ITB as well, so right now the two kinds of pilots are very similar.  Those fixups will be coming in a later PR.
> Install ITB scripts and allow selecting between production and ITB

- 10-setup-htcondor.sh
If a variable in the glidein config looked like `OSG_SITE_NAME ` (i.e. with a trailing space but no value), then the awk expression in set_var() would use `OSG_SITE_NAME ` as the value instead of the empty string.
This was fixed in GlideinWMS somewhere between 3.9.6rc4 and 3.9.6 so we should use their version once we can (so after #103 is fixed and merged).
> Fix set_var() to not use the variable name as the value if the variable has an empty value

- Dockerfile
The RPM named "singularity" has been removed from EPEL and the "provides: singularity" line has been removed from apptainer, so now we need to ask for it by name.
> Install "apptainer" instead of "singularity"

- .github/workflows/build-container.yml
- Dockerfile
Otherwise we get junk like this:
`opensciencegrid/osgvo-docker-pilot:3.6-release-opensciencegrid/osgvo-docker-pilot:3.6-cuda_11_8_0-release-20230109-2007`
> Fix advertised container tag for new build action

- supervisord_startup.sh
It never runs because we exec supervisord, which replaces the bash process.
> Remove code to run cleanup scripts in supervisord_startup.sh

- 10-setup-htcondor.sh
- Dockerfile
Add a knob to enable/disable remote syslog (it defaults to enabled). Without this there's no clean way to disable it, since setting SYSLOG_HOST to blank just makes it use the default syslog host.
> Add ENABLE_REMOTE_SYSLOG (default on)

- 10-setup-htcondor.sh
- tests/test_inside_gha.sh
We are already using apptainer for running singularity containers, but we're calling it through the /usr/bin/singularity symlink. Use the binary directly.
> Ask for apptainer by name (SOFTWARE-5401)

- 10-setup-htcondor.sh
- Dockerfile
[SOFTWARE-5222](https://opensciencegrid.atlassian.net/browse/SOFTWARE-5222)
Add a 10-char random string to the NETWORK_HOSTNAME so it's unique on places using host networking.
Also turns out I had the rules for domain names wrong -- instead of a 63-char length limit overall, it's a 63-char length limit _per dot-separated-component_ and a 255-char length limit overall. This makes generating names a bit simpler.
[SOFTWARE-5222]: https://opensciencegrid.atlassian.net/browse/SOFTWARE-5222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add GLIDEIN_RANDOMIZE_NAME knob to add a random string to the NETWORK_HOSTNAME

- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
Specifying `ITB=1` in the environment will cause the pilot to use the scripts from the `itb` frontend group, now including `additional-htcondor-config`. Config that's done in `additional-htcondor-config` will no longer be done directly in the pilot.
Setting `CONTAINER_PILOT_USE_JOB_HOOK=1` will additionally use the minimal job wrapper and job hook instead of the singularity job wrapper. The default is off but we can turn it on by default when we declare it production ready.
The singularity job wrapper is still used to run the `advertise-userenv` startd_cron.
> Allow use of the prepare-job-hook for ITB container pilots

- 10-setup-htcondor.sh
- 50-main.config
Users can now set -e OSG_PROJECT_NAME="..." to restrict what projects the pilot will serve.
Using the old GLIDEIN_Start_Extra will result in a deprecation warning.
OSPool attribute is set accordingly - True if it is an unrestricted pilot to the production OSPool CMs, False otherwise.
> SOFTWARE-5299: implemented OSG_PROJECT_RESTRICTION and OSPool tagging

- 10-setup-htcondor.sh
- Dockerfile
Use the stash/osdf plugin 'shipped with' Condor instead of having a copy in the osg-flock repo. For the backfill containers this is the RPM from the OSG repos; for glideins, the condor tarball will contain it.
We still test it, it's just that instead of enabling it when the tests pass, we disable it when the tests fail.
This is temporary - I'll move the logic into the `additional-htcondor-config` script later.
https://opensciencegrid.atlassian.net/browse/OSPOOL-64
> Use osdf-client from RPMs instead of downloading our own from the osg-flock repo (OSPOOL-64)

- 10-setup-htcondor.sh
The `$` symbol is not escaped, meaning the pilot addition dumps in a line which looks like this:
```
STARTD_ATTRS =  STASH_PLUGIN_VERSION OSDF_PLUGIN_VERSION
```
This does not inherit the prior settings of `STARTD_ATTRS`, meaning `GLIDEIN_Site` is not set.  This causes jobs to no longer be matched.
> Fix bash escaping error for STARTD_ATTRS

- Dockerfile
Nothing provides lsb_release so if we have a script that uses it, it will have to be modified.
SOFTWARE-5538
This seems to be the only change necessary to build a pilot based on the opensciencegrid/software-base/3.6-el9-development image.
> Don't install redhat-lsb-core on EL9: it doesn't exist

- 10-setup-htcondor.sh
- Dockerfile
This provides a way of adding additional bind-mounts into Singularity jobs.  This is something we can already do in factory pilots with `GLIDEIN_SINGULARITY_BINDPATH`.
`SINGULARITY_BIND_EXTRA` adds the bind-mounts by setting `GLIDEIN_SINGULARITY_BINDPATH` in the glidein config; I didn't want to couple the behavior to the implementation which is why I gave it a different name.
> Add the environment variable `SINGULARITY_BIND_EXTRA` (SOFTWARE-5528)

- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
This adds two new attributes: `GLIDEIN_ToRetire` and `GLIDEIN_ToDie`. We need these to align with the GWMS glideins in the pool. The attributes will not only be used within the container, but also for monitoring (OSPOOL-72 for example) and potentially for scheduling decisions (when we implement better logic for `JobDurationCategory`).
> GLIDEIN_ToRetire and GLIDEIN_ToDie

- Dockerfile
The bug got fixed in v4.32 so we can use master again.
> Switch CVMFSEXEC back to master

- 50-main.config
Make sure we only schedule `JobDurationCategory = "Long"` jobs on pilots which have enough runtime left to finish the job. See:
https://portal.osg-htc.org/documentation/htc_workloads/workload_planning/jobdurationcategory/
We already have a similar setup in for the GWMS pilots:
https://github.com/opensciencegrid/osg-flock/blob/master/ospool.osg-htc.org/production/frontend-template.xml#L55-L57
> Handle JobDurationCategory=Long

- Dockerfile
Caveat: this adds the requirement for git >= 2 for the `--sort=version:refname` feature, which is not available on el7.
> Add option to use the highest versioned tag of CVMFSEXEC

- .github/workflows/build-container.yml
This changes the OS-less tags (such as `3.6-release`) to be equivalent to the corresponding al8 tags (so `3.6-al8-release`).  It keeps the `al8` tags for backward compat, in case anybody is using those, it just adds the OS-less tags as aliases.
Note that this has the side effect of making tags like `3.6-el8-release` for the CentOS Stream 8-based builds, which we didn't have before.
> Change the default image OS from el8 (i.e., CentOS Stream 8) to al8 (i.e., Alma 8)

- .github/workflows/build-container.yml
Running with singularity requires converting the image to SIF first and the runner doesn't have the disk space to do that.
> Skip singularity test for cuda images

- Dockerfile
socat is useful for testing primitive network connectivity in the EP and is only 1 MB.
> Install socat into the image for network testing

- .github/workflows/build-container.yml
Also disable CUDA 23 dev images as we only needed them to initially
verify OSG 23 worked with the base CUDA image
> Enable OSG 23 release/testing images (SOFTWARE-5673)

- 10-setup-htcondor.sh
- Dockerfile
- sbin/add-extra-attributes
If you bind-mount a file containing `key=value` pairs to `/etc/osg/extra-attributes.cfg` then those attributes will be added to STARTD_ATTRS.  A new script, `/usr/local/sbin/add-extra-attributes`, parses the file and does some light validation, then appends the attributes to the pilot config file.
I put the script in a new sbin/ directory so it doesn't get mixed in with all the other random files we have; I want to reorganize the repo in a later PR to put the various config and script files in directories as opposed to having them all be at the top level.
> Allow adding arbitrary extra STARTD attributes (SOFTWARE-5324)

- entrypoint.sh
Make sure there is at least one letter in $CVMFSEXEC_REPOS so we don't think a repo is specified for a string like ` ` or `,` which could occur if $CVMFSEXEC_REPOS is built up by a script, for example.
> Better check for making sure no CVMFSEXEC_REPOS were specified

- Dockerfile
- sbin/entrypoint.sh
We have an issue where if the container uses cvmfsexec to mount repos, then a SIGTERM (as sent by docker stop) won't shut it down and we have to wait for docker to time out and send SIGKILL.
This is because cvmfsexec is pid 1 inside the container, which is special, and we have to have it explicitly forward the signals to the child processes.  If we don't use cvmfsexec, then supervisord is pid 1, and signal propagation is handled.
This commit adds `tini`, a small init system, to handle signal propagation; it is only used when we're using cvmfsexec.
> Use tini when using cvmfsexec to handle signal propagation

- 10-setup-htcondor.sh
- Dockerfile
We don't specify a separate CCB_ADDRESS in that case; also we disable remote syslog. Also toss in a special case that if POOL is "ospool" then we choose prod-ospool or itb-ospool depending on $ITB.  I like this better than having that behavior be implicit if POOL is blank.
(SOFTWARE-5383)
> If POOL is a hostname or host:port then use it as a central manager as opposed to bailing out

- 10-setup-htcondor.sh
- 50-main.config
- Dockerfile
The OSPool GPU glideins have switched to an expression to help backfill partionable GPU slots with CPU-only jobs, and leave some resources for potential future GPU jobs. `RoomForCPUOnlyJobs` is defined in:
https://github.com/opensciencegrid/osg-flock/blob/master/ospool-pilot/main/pilot/additional-htcondor-config#L95-L99
This PR aligns osgvo-docker-pilot with those glideins. The `ALLOW_CPUJOB_ON_GPUSLOT` configuration flag is removed as it never worked well.
> Replaced CPUJOB_ON_GPUSLOT with the new RoomForCPUOnlyJobs

- sbin/entrypoint.sh
I ran into two issues while trying to use this image with `apptainer run`:
- `apptainer run` put `--` into the first argument, causing `exec "$@"` to fail because it wasn't a real option
- the exec command failing did _not_ cause the script to stop
> Exit out if 'exec' fails

- Dockerfile
This is generally what we use in production.  This only affects people building by hand since the GHA uses the build arguments.
> Dockerfile: switch the defaults to OSG 23 EL9

- Dockerfile
This user has such a high UID that on some systems pulling or running with podman fails.  Adding the user is still the default (because I can't add arbitrary build args in the GHA).
> Add knob to disable adding the expanse user and group (u532362:g12497)

- 10-setup-htcondor.sh
Not sure why we're still doing this in the container and not just in the main Glidein scripts
> Use the newest public OSDF validation file

- .github/workflows/build-container.yml
Drop OSG 3.6 (EOL) and al8 OS (no longer built) from the build matrix.
> Drop 3.6 and al8 from build matrix

- .github/actions/push-digest-local/action.yaml
- .github/workflows/build-container.yml
Refactor the build matrix to include platform as an argument. Add a second job to consolidate multi-platform artifacts under a single tag in the registry. See the following documentation for a reference implementation:
https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
> OSPOOL-131: Support ARM

- sbin/add-extra-attributes
- use start kwarg in enumerate() to avoid having to add 1 to the index each time
- allow spaces around the `=` between key and value
> Some tweaks to add-extra-attributes script:

- 10-setup-htcondor.sh
Current plugin version (7.11.7) fails if the federation isn't specified and can't be determined from the URL.
> Use an osdf:// URL for the remote file for OSDF validation

- sbin/entrypoint.sh
People passing in env vars via a docker --env-file may be surprised to learn that quotes are passed through literally.  Handle that case by just deleting the quotes.
> Delete quotes in/around CVMFSEXEC_REPOS

- .github/workflows/build-container.yml
I cannot tell which of our image builds failed because the text gets chopped off.  Shorten the action names so I can see the matrix elements.
> Shorten GitHub action names so the checks don't get chopped off in the web interface

- Dockerfile
Dave says that 4.45 appears to break the installer so we're getting
cvmfs-2.10 instead of cvmfs-2.12.6
> Backversion cvmfsexec to get newer CVMFS version

- Dockerfile
This was fixed in v4.46, specifically
https://github.com/cvmfs/cvmfsexec/pull/111
> Use the latest cvmfsexec version again

- 10-setup-htcondor.sh
- Dockerfile
- tests/test_inside_gha.sh
The job hook is always in use and the var does nothing.
> Drop CONTAINER_PILOT_USE_JOB_HOOK var

- 10-setup-htcondor.sh
- Dockerfile
This is applying the same cleanup tool to containers, as we use in the glideins. For now, this is an opt-in functionality which can be enabled by passing `GARBAGE_COLLECTION=1` into the container environment.
> OSPOOL-151: Enable garbage collection for ep containers

- tests/test_inside_gha.sh
It's not entirely clear what changed but looking for the `Changing activity: Benchmarking -> Idle` sentinel in the `StartLog` no longer works. Maybe the string changed, maybe benchmarking is taking slightly longer. Either way, the HTCondor team uses `condor_who -wait` in their own tests and what's good for the goose...
> Fix failing CI due to broken startd readiness detection

- 50-main.config
We have observed ospool-ep containers start up, and accept jobs before advertise-base has finished verifying/advertising. One issue is that `OSPool` is not defined, and it makes the instance look like a "allocated" resource. This change waits for the `OSG_NODE_VALIDATED` attribute to show up - it is one of the last ones being advertised in advertise-base.
> Wait for adv-base to finish

- Dockerfile
Mat noted that we won't be able to `yum install delve` when we need it since containers start as the unpriv user
> INF-2962: ensure that Go debugger is installed
